version: "3.9"
services:
  app:
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./src:/django
    ports:
      - "8000:8000"
    image: app:django
    container_name: django_container
    command: python ./src/manage.py runserver 0.0.0.0:8000

  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=website
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

